In [2]:
!pip install numpy

In [4]:
# import문 추가
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [2]:
# 배열 구성 데이터 타입
arr.dtype

dtype('int64')

In [3]:
# 배열의 행과 열의 요소 갯수
arr.shape

(3, 4)

In [4]:
# 배열 요소의 전체 갯수
arr.size

12

In [5]:
# 리스트로부터 넘파이 배열 생성
mylist = [[1, 2, 3], [4, 5, 6]]
a1 = np.array(mylist)

print(a1)

[[1 2 3]
 [4 5 6]]


In [16]:
# mylist로부터 실수형 넘파이 배열 생성
mylist = [[1, 2, 3], [4, 5, 6]]
a2 = np.array(mylist, dtype=float)
print(a2)

[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
# 3 ~ 8 숫자로 1차원 배열 생성
a3 = np.arange(3,8)

print(a3)

[3 4 5 6 7]


In [15]:
# 2 ~ 15 중 짝수로 1차원 배열 생성
a4 = np.arange(2,16)

print(a4)

[ 2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [6]:
# 0 ~ 9의 수열로  2행, 5열의 2차원 배열 생성
d = np.arange(10).reshape(2,5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [7]:
d = np.arange(10)

# 배열 d의 요소를 거꾸로 출력
d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [9]:
d2 = d.reshape(2, -1)
# 1번 행 요소를 모두 50으로 변경
d2[0] = 50
d2

array([[50, 50, 50, 50, 50],
       [ 5,  6,  7,  8,  9]])

In [10]:
data = np.array([4, 6, 7, 3, 2, 0, 10, 1, 6])

# 2보다 크고 6보다 작은 요소만 추출
data[(data>2)&(data<6)]

array([4, 3])

In [11]:
data = np.array([4, 6, 7, 3, 2, 0, 10, 1, 6])

# 3로 나눈 나머지가 0인 요소만 추출
data[data%3==0]

array([6, 3, 0, 6])

In [12]:
# 학생들의 점수가 높은 순서로 이름 출력

name_list = np.array(['John', 'Mike', 'Sarah', 'Kate', 'Samuel'])
score_list = np.array([67, 95, 84, 98, 88])

index = np.argsort(score_list)[::-1]
print(name_list[index])

['Kate' 'Mike' 'Samuel' 'Sarah' 'John']
